Traceback (most recent call last):
  File "showdown.py", line 315, in run
    self.play_game(challenge=challenge)
  File "showdown.py", line 289, in play_game
    self.selenium.move(move.move_index, move.backup_switch, mega=move.mega, volt_turn=move.volt_turn)
  File "/Users/blankr/Desktop/pokemon/pokemon_ai/showdownai/browser.py", line 253, in move
    self.wait_for_move()
  File "/Users/blankr/Desktop/pokemon/pokemon_ai/showdownai/browser.py", line 404, in wait_for_move
    save_replay = self.driver.find_element_by_css_selector("[name='saveReplay']")
  File "/Users/blankr/Anaconda3/lib/python3.6/site-packages/selenium-2.47.1-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 397, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/Users/blankr/Anaconda3/lib/python3.6/site-packages/selenium-2.47.1-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 707, in find_element
    {'using': by, 'value': value})['value']
  File "/Users/blankr/Anaconda3/lib/python3.6/site-packages/selenium-2.47.1-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 196, in execute
    self.error_handler.check_response(response)
  File "/Users/blankr/Anaconda3/lib/python3.6/site-packages/selenium-2.47.1-py3.6.egg/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name='saveReplay']"}
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565386 (45a059dc425e08165f9a10324bd1380cc13ca363),platform=Mac OS X 10.13.4 x86_64)

